# Generated by Django 6.0.3 on 2026-08-12 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Dono'), ('member', 'Membro')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['household', 'created_at'], name='membership_household_age_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'household'), name='unique_membership_per_household')],
            },
        ),
    ]
