# Generated by Django 6.0.3 on 2026-08-14 16:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("advanced", "Avançado"),
                    ("standard", "Padrão"),
                    ("essential", "Essencial"),
                ],
                default="advanced",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                (
                    "monthly_credits",
                    models.PositiveIntegerField(
                        help_text="Créditos concedidos no início de cada mês civil."
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "plano",
                "verbose_name_plural": "planos",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="only_one_default_plan",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="household",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="households",
                to="accounts.plan",
            ),
        ),
    ]
