# Generated by Django 6.0.3 on 2026-08-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_beta_credit_grant_from_real_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingState",
            fields=[
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="onboarding",
                        serialize=False,
                        to="accounts.household",
                    ),
                ),
                ("steps_done", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "início de uso",
                "verbose_name_plural": "inícios de uso",
            },
        ),
    ]
