# Generated by Django 6.0.3 on 2026-08-15 22:57

from datetime import date

from django.conf import settings as django_settings
from django.db import migrations, models


def _configured_origin():
    """The old global floor, parsed exactly as `_projection_origin` used to."""
    raw = getattr(django_settings, "PROJECTION_ORIGIN_MONTH", None)
    if isinstance(raw, date):
        return raw.replace(day=1)
    if isinstance(raw, str) and raw.strip():
        try:
            year, month = (int(p) for p in raw.split("-")[:2])
            return date(year, month, 1)
        except (ValueError, TypeError):
            pass
    return date(2025, 11, 1)


def freeze_existing_origins(apps, schema_editor):
    """Every household that exists right now keeps the floor it has been using.

    Without this, deploying E11 would move the operator's own `acumulado`,
    because their ledger contains pre-origin seed rows the global floor was
    put there to exclude.
    """
    Household = apps.get_model("accounts", "Household")
    Household.objects.filter(projection_origin_month__isnull=True).update(
        projection_origin_month=_configured_origin()
    )


def unfreeze(apps, schema_editor):
    """Reverse: clear what the forward step wrote. The column goes away with the
    AddField's own reverse, so this only has to be non-destructive."""
    Household = apps.get_model("accounts", "Household")
    Household.objects.update(projection_origin_month=None)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_onboardingstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="projection_origin_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(freeze_existing_origins, unfreeze),
    ]
