# Generated by Django 6.0.3 on 2026-03-27 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('user_correction', 'Correção do usuário'), ('inferred', 'Inferido')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'regra de memória',
                'verbose_name_plural': 'regras de memória',
                'unique_together': {('user', 'trigger', 'field')},
            },
        ),
    ]
