# Generated by Django 6.0.3 on 2026-03-27 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_memoryrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryrule",
            name="last_used_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
