# Generated by Django 6.0.3 on 2026-08-09 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0006_assistant_usage_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["user", "-created_at"], name="chat_user_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="receiptdraft",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="draft_user_status_recent_idx"
            ),
        ),
    ]
