# Generated by Django 6.0.3 on 2026-08-09 08:55

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0008_drop_redundant_user_fk_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memoryembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="memory_embed_hnsw_cosine_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
