# Generated by Django 6.0.3 on 2026-08-12 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_household_per_existing_user"),
        ("assistant", "0011_backfill_household"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="memoryrule",
            constraint=models.UniqueConstraint(
                fields=("household", "trigger", "field"), name="unique_memory_rule_per_household"
            ),
        ),
    ]
