# Generated by Django 6.0.3 on 2026-08-12 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_household_per_existing_user"),
        ("assistant", "0011_backfill_household"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assistantusageevent",
            index=models.Index(
                fields=["household", "kind", "-created_at"], name="usage_hh_kind_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["household", "-created_at"], name="chat_hh_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="receiptdraft",
            index=models.Index(
                fields=["household", "status", "-created_at"], name="draft_hh_status_recent_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memoryrule",
            constraint=models.UniqueConstraint(
                fields=("household", "trigger", "field"), name="unique_memory_rule_per_household"
            ),
        ),
    ]
