# Generated by Django 6.0.3 on 2026-08-13 15:39

"""Drop Django's implicit FK index on `household_id` for ChatMessage and ReceiptDraft.

The twins of finances/0019. Each is a strict prefix of the composite that leads
with the same column — for ChatMessage the planner was measurably picking the
narrower index and then sorting, where chat_hh_recent_idx returns the rows in
order. See docs/architecture/query-performance-baseline.md.

Only the index changes; the column and its constraint are untouched.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_household_per_existing_user"),
        ("assistant", "0015_drop_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="household",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="accounts.household",
            ),
        ),
        migrations.AlterField(
            model_name="receiptdraft",
            name="household",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="accounts.household",
            ),
        ),
    ]
