# Generated by Django 6.0.3 on 2026-08-14 15:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0017_rename_usage_interaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Exatamente como aparece em settings, incluindo o prefixo do provedor.",
                        max_length=120,
                    ),
                ),
                ("input_per_mtok", models.DecimalField(decimal_places=6, max_digits=12)),
                ("output_per_mtok", models.DecimalField(decimal_places=6, max_digits=12)),
                ("effective_from", models.DateField()),
                (
                    "source_url",
                    models.URLField(
                        help_text="A página de preços consultada. Obrigatória: preço sem fonte é palpite.",
                        max_length=500,
                    ),
                ),
                (
                    "checked_on",
                    models.DateField(help_text="Quando esta linha foi conferida on-line."),
                ),
            ],
            options={
                "verbose_name": "preço de modelo",
                "verbose_name_plural": "preços de modelo",
                "ordering": ["model_name", "-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_name", "effective_from"), name="unique_model_price_per_date"
                    )
                ],
            },
        ),
    ]
