# Generated by Django 6.0.3 on 2026-08-14 15:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_invitation"),
        ("assistant", "0019_seed_model_prices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chat", "Conversa"),
                            ("extraction", "Extração de recibo"),
                            ("transcription", "Transcrição"),
                            ("embedding", "Embedding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=120)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("ok", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.household",
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="assistant.usageinteraction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de uso",
                "verbose_name_plural": "registros de uso",
                "indexes": [
                    models.Index(
                        fields=["household", "-created_at"], name="usagerec_hh_recent_idx"
                    ),
                    models.Index(fields=["kind", "-created_at"], name="usagerec_kind_recent_idx"),
                ],
            },
        ),
    ]
