# Generated by Django 6.0.3 on 2026-08-14 16:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0020_usage_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageinteraction",
            name="credits_charged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usageinteraction",
            name="tier",
            field=models.CharField(
                choices=[
                    ("advanced", "Avançado"),
                    ("standard", "Padrão"),
                    ("essential", "Essencial"),
                ],
                default="advanced",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CreditPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("advanced", "Avançado"),
                            ("standard", "Padrão"),
                            ("essential", "Essencial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "Texto"), ("image", "Imagem")], max_length=20
                    ),
                ),
                ("credits", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "preço em créditos",
                "verbose_name_plural": "preços em créditos",
                "ordering": ["tier", "kind"],
                "constraints": [
                    models.UniqueConstraint(fields=("tier", "kind"), name="unique_credit_price")
                ],
            },
        ),
    ]
