# Generated by Django 6.0.3 on 2026-08-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0024_seed_responses_api_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagerecord",
            name="escalation_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
