# Generated by Django 6.0.3 on 2026-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0025_usagerecord_escalation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelprice",
            name="cached_input_per_mtok",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Tarifa de tokens de entrada já em cache. Vazio = cobra a tarifa cheia.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
