# Generated by Django 6.0.3 on 2026-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0026_modelprice_cached_input_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagerecord",
            name="cache_read_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
