# Generated by Django 6.0.3 on 2026-03-26 16:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("budget_ceiling", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "historical_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Média histórica (computada a partir das entradas)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "quarterly_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Média dos últimos 3 meses (computada a partir das entradas)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
