# Generated by Django 6.0.3 on 2026-03-26 16:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Dinheiro"),
                            ("pix", "Pix"),
                            ("credit_card", "Cartão de Crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Dia de fechamento da fatura (apenas cartão de crédito)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "forma de pagamento",
                "verbose_name_plural": "formas de pagamento",
                "ordering": ["name"],
            },
        ),
    ]
