# Generated by Django 6.0.3 on 2026-03-26 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_installmentplan_systemicexpense_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="closing_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Dia de fechamento da fatura (apenas cartão de crédito)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
