# Generated by Django 6.0.3 on 2026-08-09 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0009_budget_category_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["user", "billing_month", "entry_type"], name="entry_user_billing_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["user", "-date", "-created_at"], name="entry_user_date_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["user", "month"], name="income_user_month_idx"),
        ),
    ]
