# Generated by Django 6.0.3 on 2026-08-09 16:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0011_drop_redundant_user_fk_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("import_type", models.CharField(default="regular", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando a importação rodou. Nulo = preparada, ainda não executada.",
                        null=True,
                    ),
                ),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de importação",
                "verbose_name_plural": "lotes de importação",
                "ordering": ["-created_at"],
            },
        ),
    ]
