# Generated by Django 6.0.3 on 2026-08-12 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_household_per_existing_user"),
        ("finances", "0014_backfill_household"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["household", "billing_month", "entry_type"],
                name="entry_hh_billing_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["household", "-date", "-created_at"], name="entry_hh_date_recent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="income",
            index=models.Index(fields=["household", "month"], name="income_hh_month_idx"),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="unique_budget_per_household"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="unique_category_per_household"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="unique_payment_method_per_household"
            ),
        ),
    ]
