"""ImportBatch becomes ImportJob, and gains everything E12 needs.

RenameModel, not delete-and-create: production holds real import records and
the counts on them are the only history of what landed. Reversible -- the
reverse renames the table back and drops the added columns, which is lossless
for anything that existed before this migration.

Hand-written rather than autogenerated. `makemigrations` run non-interactively
cannot ask "did you rename ImportBatch to ImportJob?", so it emitted
DeleteModel + CreateModel -- which drops the table and every production import
record with it. The operations below are the same end state, arrived at without
destroying data.
"""

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_backfill_onboarding_for_existing_households"),
        ("finances", "0019_drop_redundant_household_fk_indexes"),
    ]

    operations = [
        migrations.RenameModel(old_name="ImportBatch", new_name="ImportJob"),
        migrations.AlterModelOptions(
            name="importjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "importação",
                "verbose_name_plural": "importações",
            },
        ),
        migrations.AddField(
            model_name="importjob",
            name="storage_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Chave do arquivo no armazenamento de objetos.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="original_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Enviado"),
                    ("mapped", "Mapeado"),
                    ("running", "Importando"),
                    ("done", "Concluído"),
                    ("failed", "Falhou"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="column_mapping",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importjob",
            name="skip_lines",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="category_resolutions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importjob",
            name="pm_resolutions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="importjob",
            name="total_rows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="processed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="failures",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="failures_truncated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Em pt-BR: o que deu errado e o que fazer. Mostrado ao usuário.",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # A row that predates E12 ran under the old view, which set
        # executed_at on success and nothing else. Backfilling it to DONE is
        # what stops the history page reporting every past import as "Enviado".
        migrations.RunSQL(
            sql="UPDATE finances_importjob SET status = 'done' WHERE executed_at IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="importjob",
            name="executed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a importação terminou. Nulo = preparada ou em execução.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["household", "-created_at"], name="importjob_hh_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["status", "started_at"], name="importjob_status_started_idx"
            ),
        ),
    ]
