# Generated by Django 6.0.3 on 2026-08-16 20:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_backfill_onboarding_for_existing_households"),
        ("finances", "0020_importjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Na fila"),
                            ("running", "Gerando"),
                            ("done", "Pronta"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, default="", max_length=500)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.household",
                    ),
                ),
            ],
            options={
                "verbose_name": "exportação",
                "verbose_name_plural": "exportações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["household", "-created_at"], name="exportjob_hh_recent_idx"
                    )
                ],
            },
        ),
    ]
