# Generated by Django 6.0.3 on 2026-08-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0021_exportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Enviado"),
                    ("mapped", "Mapeado"),
                    ("queued", "Na fila"),
                    ("running", "Importando"),
                    ("done", "Concluído"),
                    ("failed", "Falhou"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
