"""A household's data, in a form this product can read back.

Two audiences, one archive. The CSVs are for *this* importer: they use its
headers, its date format and its amount format, so an export is a valid input to
the wizard that produced it. ``ledger.json`` is for everything else -- the
fields no CSV column exists for, the models the importer cannot create, and the
chat history, which E12 decision 3 keeps out of the CSVs on purpose.

``entradas.csv`` deliberately omits installment-derived entries. They are
regenerated by ``InstallmentPlan.generate_entries()`` when
``parcelamentos.csv`` is imported, so shipping both would double every
parcelled purchase on re-import.
"""

import csv
import io
import json
import zipfile
from datetime import date, datetime
from decimal import Decimal

from django.utils import timezone

ARCHIVE_MEMBERS = (
    "entradas.csv",
    "parcelamentos.csv",
    "receitas.csv",
    "categorias.csv",
    "formas_pagamento.csv",
    "orcamentos.csv",
    "despesas_sistemicas.csv",
    "ledger.json",
    "LEIA-ME.txt",
)

# Excel reads a BOM-less UTF-8 file as Latin-1. The audience opens these in
# Excel, and "Alimentação" rendering as "AlimentaÃ§Ã£o" is the difference
# between a usable export and a support ticket.
BOM = "﻿"


def format_amount(value) -> str:
    """pt-BR, and re-parseable by ``csv_parser.parse_amount``.

    No thousands separator: ``parse_amount`` accepts both forms, and emitting
    the simpler one removes a way for the round trip to be wrong.

    ``None`` becomes an empty cell rather than ``0,00``. ``Category``'s
    ``historical_avg`` and ``quarterly_avg`` are nullable and mean "never
    computed"; writing a zero would export a number the household does not
    have, and on re-import it would read as a real average of nothing.
    """
    if value is None:
        return ""
    return f"{Decimal(value):.2f}".replace(".", ",")


def format_date(value: date) -> str:
    """``dd/mm/yyyy`` -- the only format ``csv_parser.parse_date`` accepts."""
    return value.strftime("%d/%m/%Y")


def _csv_bytes(header: list[str], rows) -> bytes:
    buffer = io.StringIO()
    buffer.write(BOM)
    writer = csv.writer(buffer)
    writer.writerow(header)
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


def _json_default(value):
    if isinstance(value, Decimal):
        # A string, not a float: a float turns R$ 0,10 into 0.1000000000000000055
        # and this file is a financial record.
        return str(value)
    if isinstance(value, datetime | date):
        return value.isoformat()
    return str(value)


def build_export(household) -> bytes:
    """The whole archive, in memory.

    In memory because it is bounded: one household's ledger is measured in
    megabytes, and streaming would buy nothing while making the task harder to
    reason about. If a household ever exports something a Cloud Run instance
    cannot hold, that is the signal to chunk -- not a reason to pre-emptively
    complicate this.
    """
    from accounts.models import Invitation, Membership
    from assistant.models import ChatMessage, MemoryRule, ReceiptDraft, UsageInteraction
    from core.models import Consent, Feedback, PolicyAcceptance, ProductEvent
    from finances.models import (
        Budget,
        Category,
        Entry,
        ExportJob,
        ImportJob,
        Income,
        InstallmentPlan,
        PaymentMethod,
        PaymentMethodClosingDay,
        SystemicExpense,
    )

    entries = list(
        Entry.objects.for_household(household)
        .filter(installment_plan__isnull=True)
        .select_related("category", "payment_method")
        .order_by("date", "id")
    )
    all_entries = list(
        Entry.objects.for_household(household)
        .select_related("category", "payment_method")
        .order_by("date", "id")
    )
    plans = list(
        InstallmentPlan.objects.for_household(household)
        .select_related("category", "payment_method")
        .order_by("date", "id")
    )
    incomes = list(Income.objects.for_household(household).order_by("month", "id"))
    categories = list(
        Category.objects.for_household(household).select_related("budget").order_by("name")
    )
    payment_methods = list(PaymentMethod.objects.for_household(household).order_by("name"))
    budgets = list(Budget.objects.for_household(household).order_by("name"))
    systemic = list(
        SystemicExpense.objects.for_household(household)
        .select_related("category", "payment_method")
        .order_by("name")
    )
    closing_days = list(
        PaymentMethodClosingDay.objects.filter(payment_method__household=household)
        .select_related("payment_method")
        .order_by("month")
    )

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(
            "entradas.csv",
            _csv_bytes(
                ["data", "valor", "descrição", "categoria", "forma"],
                [
                    [
                        format_date(entry.date),
                        format_amount(entry.amount),
                        entry.description,
                        entry.category.name if entry.category else "",
                        entry.payment_method.name if entry.payment_method else "",
                    ]
                    for entry in entries
                ],
            ),
        )
        archive.writestr(
            "parcelamentos.csv",
            _csv_bytes(
                ["data", "valor", "descrição", "categoria", "forma", "parcelas", "valor_parcela"],
                [
                    [
                        format_date(plan.date),
                        format_amount(plan.total_amount),
                        plan.description,
                        plan.category.name if plan.category else "",
                        plan.payment_method.name if plan.payment_method else "",
                        plan.num_installments,
                        format_amount(plan.installment_amount),
                    ]
                    for plan in plans
                ],
            ),
        )
        archive.writestr(
            "receitas.csv",
            _csv_bytes(
                ["nome", "valor", "mês", "recorrente", "início", "fim"],
                [
                    [
                        income.name,
                        format_amount(income.amount),
                        format_date(income.month),
                        "sim" if income.is_recurring else "não",
                        format_date(income.recurrence_start) if income.recurrence_start else "",
                        format_date(income.recurrence_end) if income.recurrence_end else "",
                    ]
                    for income in incomes
                ],
            ),
        )
        archive.writestr(
            "categorias.csv",
            _csv_bytes(
                ["nome", "orçamento", "teto", "média_histórica"],
                [
                    [
                        category.name,
                        category.budget.name if category.budget else "",
                        format_amount(category.budget_ceiling),
                        format_amount(category.historical_avg),
                    ]
                    for category in categories
                ],
            ),
        )
        archive.writestr(
            "formas_pagamento.csv",
            _csv_bytes(
                ["nome", "tipo", "dia_fechamento", "ativa"],
                [
                    [
                        payment.name,
                        payment.type,
                        payment.closing_day or "",
                        "sim" if payment.is_active else "não",
                    ]
                    for payment in payment_methods
                ],
            ),
        )
        archive.writestr(
            "orcamentos.csv",
            _csv_bytes(
                ["nome", "valor"],
                [[budget.name, format_amount(budget.amount)] for budget in budgets],
            ),
        )
        archive.writestr(
            "despesas_sistemicas.csv",
            _csv_bytes(
                ["nome", "valor_padrão", "categoria", "forma", "ativa"],
                [
                    [
                        expense.name,
                        format_amount(expense.default_amount),
                        expense.category.name if expense.category else "",
                        expense.payment_method.name if expense.payment_method else "",
                        "sim" if expense.is_active else "não",
                    ]
                    for expense in systemic
                ],
            ),
        )

        payload = {
            "meta": {
                "gerado_em": timezone.now().isoformat(),
                "domicilio": str(household.pk),
                # 2: E13 added `conta`, `eventos`, `feedbacks`, `uso` and
                # `exportacoes`. Adding keys breaks no reader, but the number is
                # what tells a person which shape they are holding.
                "formato": 2,
            },
            "entradas": [
                {
                    "id": str(entry.id),
                    "data": entry.date,
                    "valor": entry.amount,
                    "descricao": entry.description,
                    "categoria": entry.category.name if entry.category else None,
                    "forma": entry.payment_method.name if entry.payment_method else None,
                    "tipo": entry.entry_type,
                    "mes_fatura": entry.billing_month,
                    "mes_fatura_manual": entry.billing_month_override,
                    "parcelamento": str(entry.installment_plan_id)
                    if entry.installment_plan_id
                    else None,
                    "criado_em": entry.created_at,
                }
                for entry in all_entries
            ],
            "parcelamentos": [
                {
                    "id": str(plan.id),
                    "data": plan.date,
                    "descricao": plan.description,
                    "valor_total": plan.total_amount,
                    "parcelas": plan.num_installments,
                    "valor_parcela": plan.installment_amount,
                    "categoria": plan.category.name if plan.category else None,
                    "forma": plan.payment_method.name if plan.payment_method else None,
                }
                for plan in plans
            ],
            "receitas": [
                {
                    "nome": income.name,
                    "valor": income.amount,
                    "mes": income.month,
                    "recorrente": income.is_recurring,
                    "inicio": income.recurrence_start,
                    "fim": income.recurrence_end,
                }
                for income in incomes
            ],
            "categorias": [
                {
                    "nome": category.name,
                    "orcamento": category.budget.name if category.budget else None,
                    "teto": category.budget_ceiling,
                    "media_historica": category.historical_avg,
                    "media_trimestral": category.quarterly_avg,
                    "do_sistema": category.is_system,
                }
                for category in categories
            ],
            "formas_pagamento": [
                {
                    "nome": payment.name,
                    "tipo": payment.type,
                    "dia_fechamento": payment.closing_day,
                    "ativa": payment.is_active,
                }
                for payment in payment_methods
            ],
            "orcamentos": [{"nome": budget.name, "valor": budget.amount} for budget in budgets],
            "despesas_sistemicas": [
                {
                    "nome": expense.name,
                    "valor_padrao": expense.default_amount,
                    "categoria": expense.category.name if expense.category else None,
                    "forma": expense.payment_method.name if expense.payment_method else None,
                    "ativa": expense.is_active,
                }
                for expense in systemic
            ],
            "fechamentos": [
                {
                    "forma": override.payment_method.name,
                    "mes": override.month,
                    "dia_fechamento": override.closing_day,
                }
                for override in closing_days
            ],
            # E12 decision 3: the chat lives here and nowhere else in the
            # archive. E13 owns the retention policy; this epic implements the
            # portability.
            "conversas": [
                {
                    "papel": message.role,
                    "conteudo": message.content,
                    "criado_em": message.created_at,
                }
                for message in ChatMessage.objects.for_household(household).order_by("created_at")
            ],
            "regras_memoria": [
                {
                    "gatilho": rule.trigger,
                    "campo": rule.field,
                    "valor": rule.value,
                    "origem": rule.source,
                }
                for rule in MemoryRule.objects.for_household(household).order_by("created_at")
            ],
            "rascunhos_recibo": [
                {"situacao": draft.status, "criado_em": draft.created_at}
                for draft in ReceiptDraft.objects.for_household(household).order_by("created_at")
            ],
            "importacoes": [
                {
                    "arquivo": job.original_filename,
                    "situacao": job.status,
                    "importados": job.created_count,
                    "pulados": job.skipped_count,
                    "erros": job.error_count,
                    "criado_em": job.created_at,
                }
                for job in ImportJob.objects.for_household(household).order_by("created_at")
            ],
            # E13. The other half of the job history: when a copy of this data
            # was asked for. The archive itself expires after 7 days; this row
            # is what says it once existed.
            "exportacoes": [
                {
                    "situacao": job.status,
                    "tamanho_bytes": job.size_bytes,
                    "criado_em": job.created_at,
                    "concluido_em": job.completed_at,
                }
                for job in ExportJob.objects.for_household(household).order_by("created_at")
            ],
            # E13. The account itself: an access request that omits "which
            # address, since when, which version you accepted" is not one.
            # `password` is deliberately absent — an export is a file people
            # email to themselves, and a hash in an inbox is a credential in
            # an inbox.
            "conta": {
                "casa": {
                    "nome": household.name,
                    "criada_em": household.created_at,
                },
                "pessoas": [
                    {
                        "email": membership.user.email,
                        "nome": membership.user.first_name,
                        "papel": membership.role,
                        "entrou_em": membership.created_at,
                    }
                    for membership in Membership.objects.filter(household=household)
                    .select_related("user")
                    .order_by("created_at")
                ],
                "convites": [
                    {
                        "email": invitation.email,
                        "criado_em": invitation.created_at,
                        "aceito_em": invitation.accepted_at,
                        "cancelado_em": invitation.revoked_at,
                    }
                    for invitation in Invitation.objects.for_household(household).order_by(
                        "created_at"
                    )
                ],
                "aceites": [
                    {
                        "documento": acceptance.document,
                        "versao": acceptance.version,
                        "aceito_em": acceptance.accepted_at,
                    }
                    for acceptance in PolicyAcceptance.objects.filter(
                        user__memberships__household=household
                    ).order_by("accepted_at")
                ],
                "consentimentos": [
                    {
                        "finalidade": consent.purpose,
                        "concedido": consent.granted,
                        "concedido_em": consent.granted_at,
                        "retirado_em": consent.revoked_at,
                    }
                    for consent in Consent.objects.filter(
                        user__memberships__household=household
                    ).order_by("updated_at")
                ],
            },
            # E13. `core.ProductEvent`'s docstring has said "exported by E13"
            # since E14 shipped; this is that promise. No user content is in
            # here by construction — the model forbids it.
            "eventos": [
                {
                    "nome": event.name,
                    "criado_em": event.created_at,
                    "detalhes": event.metadata,
                }
                for event in ProductEvent.objects.for_household(household).order_by("created_at")
            ],
            # E13. The one table that holds user-authored text on purpose.
            "feedbacks": [
                {"mensagem": item.message, "criado_em": item.created_at}
                for item in Feedback.objects.for_household(household).order_by("created_at")
            ],
            # E13. What the AI cost. Kept for 730 days under legítimo interesse,
            # so a person asking what we hold about them is entitled to see it.
            "uso": [
                {
                    "tipo": interaction.kind,
                    "faixa": interaction.tier,
                    "creditos": interaction.credits_charged,
                    "criado_em": interaction.created_at,
                }
                for interaction in UsageInteraction.objects.for_household(household).order_by(
                    "created_at"
                )
            ],
        }
        archive.writestr(
            "ledger.json",
            json.dumps(payload, default=_json_default, ensure_ascii=False, indent=2).encode(),
        )
        archive.writestr("LEIA-ME.txt", _readme().encode())

    return buffer.getvalue()


def _readme() -> str:
    return """Exportação dos seus dados — Ledger

O que tem aqui
--------------
entradas.csv            Suas entradas avulsas, no formato que o próprio Ledger
                        importa. Não inclui as parcelas geradas por um
                        parcelamento — elas são recriadas ao importar
                        parcelamentos.csv, e incluir as duas coisas dobraria
                        cada compra parcelada.
parcelamentos.csv       Suas compras parceladas.
receitas.csv            Suas receitas, inclusive as recorrentes.
categorias.csv          Suas categorias, com teto e médias.
formas_pagamento.csv    Suas formas de pagamento e o dia de fechamento.
orcamentos.csv          Seus orçamentos.
despesas_sistemicas.csv Suas despesas fixas.
ledger.json             Tudo acima, sem perder nenhum campo, mais o histórico
                        de conversas com o assistente, as regras de memória, o
                        registro das importações, os dados da sua conta (quem
                        está na casa, quais versões dos documentos você aceitou,
                        se autorizou o uso de IA), os eventos de uso do produto,
                        os comentários que você enviou e quanto o assistente
                        custou em créditos.

Como trazer de volta
--------------------
1. Crie ou entre no domicílio de destino.
2. Cadastre as categorias e formas de pagamento (categorias.csv e
   formas_pagamento.csv listam as que você tinha) — ou deixe o importador
   criá-las na etapa de conflitos.
3. Importar CSV → envie entradas.csv como "Entradas regulares".
4. Importar CSV → envie parcelamentos.csv como "Parcelamentos".

Os valores estão em formato brasileiro (1234,56) e as datas em dd/mm/aaaa,
que é o que o importador do Ledger espera.

Este arquivo contém seu histórico financeiro completo. Guarde-o com o mesmo
cuidado que você teria com um extrato bancário.
"""
