# Generated by Django 6.0.3 on 2026-08-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "tentativa de login",
                "verbose_name_plural": "tentativas de login",
                "indexes": [
                    models.Index(
                        fields=["username", "-created_at"], name="login_username_recent_idx"
                    ),
                    models.Index(fields=["ip", "-created_at"], name="login_ip_recent_idx"),
                ],
            },
        ),
    ]
