# Generated by Django 6.0.3 on 2026-08-13 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_seed_email_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "acesso administrativo",
                "verbose_name_plural": "acessos administrativos",
                "indexes": [
                    models.Index(fields=["actor", "-created_at"], name="adminlog_actor_recent_idx")
                ],
            },
        ),
    ]
