# Generated by Django 6.0.3 on 2026-08-15 18:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_admin_access_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("done", "Concluída"),
                            ("dead", "Descartada"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("request_id", models.CharField(blank=True, default="", max_length=32)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "execução de tarefa",
                "verbose_name_plural": "execuções de tarefa",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="taskrun_status_recent_idx"
                    ),
                    models.Index(fields=["name", "-created_at"], name="taskrun_name_recent_idx"),
                ],
            },
        ),
    ]
