# Generated by Django 6.0.3 on 2026-08-15 21:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_beta_credit_grant_from_real_usage"),
        ("core", "0006_taskrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("once", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="accounts.household",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de produto",
                "verbose_name_plural": "eventos de produto",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name", "-created_at"], name="event_name_recent_idx"),
                    models.Index(fields=["household", "-created_at"], name="event_hh_recent_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("once", True)),
                        fields=("household", "name"),
                        name="one_once_event_per_household",
                    )
                ],
            },
        ),
    ]
