# Generated by Django 6.0.3 on 2026-08-17 20:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "purpose",
                    models.CharField(choices=[("ai_assistant", "Assistente de IA")], max_length=30),
                ),
                ("granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "consentimento",
                "verbose_name_plural": "consentimentos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "purpose"), name="one_consent_per_purpose"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        choices=[("privacy", "Aviso de privacidade"), ("terms", "Termos de uso")],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "aceite de política",
                "verbose_name_plural": "aceites de política",
                "ordering": ["-accepted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "document", "version"), name="one_acceptance_per_version"
                    )
                ],
            },
        ),
    ]
